version: '3.8'

services:
  # Redis for Celery broker
  redis:
    image: redis:7-alpine
    container_name: personal-q-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal-q-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./data/personal_q.db
      - CHROMA_DB_PATH=./data/chromadb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - backend_data:/app/data
      - ./backend:/app
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Celery Worker
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal-q-celery-worker
    command: celery -A app.workers.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./data/personal_q.db
      - CHROMA_DB_PATH=./data/chromadb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - backend_data:/app/data
      - ./backend:/app
    depends_on:
      redis:
        condition: service_healthy

  # Celery Beat (Scheduler)
  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal-q-celery-beat
    command: celery -A app.workers.celery_app beat --loglevel=info
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./data/personal_q.db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - backend_data:/app/data
      - ./backend:/app
    depends_on:
      redis:
        condition: service_healthy

  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: personal-q-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - frontend_node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy

volumes:
  backend_data:
  redis_data:
  frontend_node_modules:
